// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go
//
// Generated by this command:
//
//	mockgen -source=order_service.go -destination=../mocks/order/order_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	order "go-gadget-api/internal/order"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockService) Cancel(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockServiceMockRecorder) Cancel(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockService)(nil).Cancel), ctx, orderID)
}

// Checkout mocks base method.
func (m *MockService) Checkout(ctx context.Context, userID string, req order.CheckoutRequest) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, userID, req)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkout indicates an expected call of Checkout.
func (mr *MockServiceMockRecorder) Checkout(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockService)(nil).Checkout), ctx, userID, req)
}

// Complete mocks base method.
func (m *MockService) Complete(ctx context.Context, orderID, nextStatus string) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, orderID, nextStatus)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockServiceMockRecorder) Complete(ctx, orderID, nextStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockService)(nil).Complete), ctx, orderID, nextStatus)
}

// Detail mocks base method.
func (m *MockService) Detail(ctx context.Context, orderID string) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, orderID)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockServiceMockRecorder) Detail(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockService)(nil).Detail), ctx, orderID)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, userID, status string, page, limit int) ([]order.OrderResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, status, page, limit)
	ret0, _ := ret[0].([]order.OrderResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, userID, status, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, userID, status, page, limit)
}

// ListAdmin mocks base method.
func (m *MockService) ListAdmin(ctx context.Context, status, search string, page, limit int) ([]order.OrderResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdmin", ctx, status, search, page, limit)
	ret0, _ := ret[0].([]order.OrderResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAdmin indicates an expected call of ListAdmin.
func (mr *MockServiceMockRecorder) ListAdmin(ctx, status, search, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdmin", reflect.TypeOf((*MockService)(nil).ListAdmin), ctx, status, search, page, limit)
}

// UpdateStatusByAdmin mocks base method.
func (m *MockService) UpdateStatusByAdmin(ctx context.Context, orderID, nextStatus string, receiptNo *string) (order.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByAdmin", ctx, orderID, nextStatus, receiptNo)
	ret0, _ := ret[0].(order.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusByAdmin indicates an expected call of UpdateStatusByAdmin.
func (mr *MockServiceMockRecorder) UpdateStatusByAdmin(ctx, orderID, nextStatus, receiptNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByAdmin", reflect.TypeOf((*MockService)(nil).UpdateStatusByAdmin), ctx, orderID, nextStatus, receiptNo)
}
