// Code generated by MockGen. DO NOT EDIT.
// Source: customer_service.go
//
// Generated by this command:
//
//	mockgen -source=customer_service.go -destination=../mock/customer/customer_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	customer "go-gadget-api/internal/customer"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetCustomerByID mocks base method.
func (m *MockService) GetCustomerByID(ctx context.Context, req customer.CustomerDetailsRequest) (customer.CustomerDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByID", ctx, req)
	ret0, _ := ret[0].(customer.CustomerDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomerByID indicates an expected call of GetCustomerByID.
func (mr *MockServiceMockRecorder) GetCustomerByID(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByID", reflect.TypeOf((*MockService)(nil).GetCustomerByID), ctx, req)
}

// ListCustomerAddresses mocks base method.
func (m *MockService) ListCustomerAddresses(ctx context.Context, req customer.CustomerAddressesRequest) (customer.PaginatedAddressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomerAddresses", ctx, req)
	ret0, _ := ret[0].(customer.PaginatedAddressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomerAddresses indicates an expected call of ListCustomerAddresses.
func (mr *MockServiceMockRecorder) ListCustomerAddresses(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomerAddresses", reflect.TypeOf((*MockService)(nil).ListCustomerAddresses), ctx, req)
}

// ListCustomerOrders mocks base method.
func (m *MockService) ListCustomerOrders(ctx context.Context, req customer.CustomerOrdersRequest) (customer.PaginatedOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomerOrders", ctx, req)
	ret0, _ := ret[0].(customer.PaginatedOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomerOrders indicates an expected call of ListCustomerOrders.
func (mr *MockServiceMockRecorder) ListCustomerOrders(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomerOrders", reflect.TypeOf((*MockService)(nil).ListCustomerOrders), ctx, req)
}

// ListCustomers mocks base method.
func (m *MockService) ListCustomers(ctx context.Context, page, limit int, search string) ([]customer.CustomerListResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, page, limit, search)
	ret0, _ := ret[0].([]customer.CustomerListResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockServiceMockRecorder) ListCustomers(ctx, page, limit, search any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockService)(nil).ListCustomers), ctx, page, limit, search)
}

// ToggleCustomerStatus mocks base method.
func (m *MockService) ToggleCustomerStatus(ctx context.Context, customerID string, active bool) (customer.CustomerListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleCustomerStatus", ctx, customerID, active)
	ret0, _ := ret[0].(customer.CustomerListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleCustomerStatus indicates an expected call of ToggleCustomerStatus.
func (mr *MockServiceMockRecorder) ToggleCustomerStatus(ctx, customerID, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleCustomerStatus", reflect.TypeOf((*MockService)(nil).ToggleCustomerStatus), ctx, customerID, active)
}

// UpdateProfile mocks base method.
func (m *MockService) UpdateProfile(ctx context.Context, customerID string, req customer.UpdateProfileRequest) (customer.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, customerID, req)
	ret0, _ := ret[0].(customer.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockServiceMockRecorder) UpdateProfile(ctx, customerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockService)(nil).UpdateProfile), ctx, customerID, req)
}
