// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_tokens.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteEmailConfirmationTokenByPin = `-- name: DeleteEmailConfirmationTokenByPin :exec
DELETE FROM email_confirmation_tokens WHERE pin = $1
`

func (q *Queries) DeleteEmailConfirmationTokenByPin(ctx context.Context, pin string) error {
	_, err := q.exec(ctx, q.deleteEmailConfirmationTokenByPinStmt, deleteEmailConfirmationTokenByPin, pin)
	return err
}

const deleteEmailConfirmationTokenByToken = `-- name: DeleteEmailConfirmationTokenByToken :exec
DELETE FROM email_confirmation_tokens WHERE token = $1
`

func (q *Queries) DeleteEmailConfirmationTokenByToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deleteEmailConfirmationTokenByTokenStmt, deleteEmailConfirmationTokenByToken, token)
	return err
}

const deleteEmailConfirmationTokensByUserID = `-- name: DeleteEmailConfirmationTokensByUserID :exec
DELETE FROM email_confirmation_tokens WHERE user_id = $1
`

func (q *Queries) DeleteEmailConfirmationTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteEmailConfirmationTokensByUserIDStmt, deleteEmailConfirmationTokensByUserID, userID)
	return err
}

const deletePasswordResetTokenByToken = `-- name: DeletePasswordResetTokenByToken :exec
DELETE FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) DeletePasswordResetTokenByToken(ctx context.Context, token string) error {
	_, err := q.exec(ctx, q.deletePasswordResetTokenByTokenStmt, deletePasswordResetTokenByToken, token)
	return err
}

const getEmailConfirmationTokenByToken = `-- name: GetEmailConfirmationTokenByToken :one
SELECT id, user_id, token, pin, created_at, expires_at
FROM email_confirmation_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetEmailConfirmationTokenByToken(ctx context.Context, token string) (EmailConfirmationToken, error) {
	row := q.queryRow(ctx, q.getEmailConfirmationTokenByTokenStmt, getEmailConfirmationTokenByToken, token)
	var i EmailConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Pin,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLatestEmailConfirmationTokenByUserID = `-- name: GetLatestEmailConfirmationTokenByUserID :one
SELECT id, user_id, token, pin, created_at, expires_at
FROM email_confirmation_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestEmailConfirmationTokenByUserID(ctx context.Context, userID uuid.UUID) (EmailConfirmationToken, error) {
	row := q.queryRow(ctx, q.getLatestEmailConfirmationTokenByUserIDStmt, getLatestEmailConfirmationTokenByUserID, userID)
	var i EmailConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Pin,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLatestPasswordResetTokenByUserID = `-- name: GetLatestPasswordResetTokenByUserID :one
SELECT id, user_id, token, created_at, expires_at
FROM password_reset_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPasswordResetTokenByUserID(ctx context.Context, userID uuid.UUID) (PasswordResetToken, error) {
	row := q.queryRow(ctx, q.getLatestPasswordResetTokenByUserIDStmt, getLatestPasswordResetTokenByUserID, userID)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, created_at, expires_at
FROM password_reset_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.queryRow(ctx, q.getPasswordResetTokenStmt, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setUserEmailConfirmed = `-- name: SetUserEmailConfirmed :exec
UPDATE users
SET email_confirmed = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SetUserEmailConfirmed(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.setUserEmailConfirmedStmt, setUserEmailConfirmed, id)
	return err
}

const upsertEmailConfirmationToken = `-- name: UpsertEmailConfirmationToken :exec
INSERT INTO email_confirmation_tokens (user_id, token, pin, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
DO UPDATE SET token = EXCLUDED.token, pin = EXCLUDED.pin, expires_at = EXCLUDED.expires_at, created_at = EXCLUDED.created_at
`

type UpsertEmailConfirmationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	Pin       string    `json:"pin"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpsertEmailConfirmationToken(ctx context.Context, arg UpsertEmailConfirmationTokenParams) error {
	_, err := q.exec(ctx, q.upsertEmailConfirmationTokenStmt, upsertEmailConfirmationToken,
		arg.UserID,
		arg.Token,
		arg.Pin,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const upsertPasswordResetToken = `-- name: UpsertPasswordResetToken :exec
INSERT INTO password_reset_tokens (user_id, token, expires_at, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id)
DO UPDATE SET token = EXCLUDED.token, expires_at = EXCLUDED.expires_at, created_at = EXCLUDED.created_at
`

type UpsertPasswordResetTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpsertPasswordResetToken(ctx context.Context, arg UpsertPasswordResetTokenParams) error {
	_, err := q.exec(ctx, q.upsertPasswordResetTokenStmt, upsertPasswordResetToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
