// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCategoryDistribution = `-- name: GetCategoryDistribution :many
SELECT 
    c.name as category_name,
    COUNT(p.id) as product_count
FROM categories c
LEFT JOIN products p ON c.id = p.category_id AND p.deleted_at IS NULL
WHERE c.deleted_at IS NULL
GROUP BY c.id, c.name
ORDER BY product_count DESC
`

type GetCategoryDistributionRow struct {
	CategoryName string `json:"category_name"`
	ProductCount int64  `json:"product_count"`
}

func (q *Queries) GetCategoryDistribution(ctx context.Context) ([]GetCategoryDistributionRow, error) {
	rows, err := q.query(ctx, q.getCategoryDistributionStmt, getCategoryDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryDistributionRow
	for rows.Next() {
		var i GetCategoryDistributionRow
		if err := rows.Scan(&i.CategoryName, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM products WHERE deleted_at IS NULL) AS total_products,
    (SELECT COUNT(*) FROM brands WHERE deleted_at IS NULL) AS total_brands,
    (SELECT COUNT(*) FROM categories WHERE deleted_at IS NULL) AS total_categories,
    (SELECT COUNT(*) FROM users WHERE role = 'CUSTOMER') AS total_customers,
    (SELECT COUNT(*) FROM orders WHERE deleted_at IS NULL) AS total_orders,
    (SELECT COALESCE(SUM(total_price::numeric), 0) FROM orders WHERE status = 'COMPLETED' AND deleted_at IS NULL) AS total_revenue
`

type GetDashboardStatsRow struct {
	TotalProducts   int64       `json:"total_products"`
	TotalBrands     int64       `json:"total_brands"`
	TotalCategories int64       `json:"total_categories"`
	TotalCustomers  int64       `json:"total_customers"`
	TotalOrders     int64       `json:"total_orders"`
	TotalRevenue    interface{} `json:"total_revenue"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.queryRow(ctx, q.getDashboardStatsStmt, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalProducts,
		&i.TotalBrands,
		&i.TotalCategories,
		&i.TotalCustomers,
		&i.TotalOrders,
		&i.TotalRevenue,
	)
	return i, err
}

const listRecentOrders = `-- name: ListRecentOrders :many
SELECT 
    o.id,
    o.order_number,
    o.total_price,
    o.status,
    u.name AS user_name,
    o.placed_at
FROM orders o
JOIN users u ON o.user_id = u.id
WHERE o.deleted_at IS NULL
ORDER BY o.placed_at DESC
LIMIT $1
`

type ListRecentOrdersRow struct {
	ID          uuid.UUID `json:"id"`
	OrderNumber string    `json:"order_number"`
	TotalPrice  string    `json:"total_price"`
	Status      string    `json:"status"`
	UserName    string    `json:"user_name"`
	PlacedAt    time.Time `json:"placed_at"`
}

func (q *Queries) ListRecentOrders(ctx context.Context, limit int32) ([]ListRecentOrdersRow, error) {
	rows, err := q.query(ctx, q.listRecentOrdersStmt, listRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentOrdersRow
	for rows.Next() {
		var i ListRecentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.TotalPrice,
			&i.Status,
			&i.UserName,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
