// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCartItemStmt, err = db.PrepareContext(ctx, addCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddCartItem: %w", err)
	}
	if q.addWishlistItemStmt, err = db.PrepareContext(ctx, addWishlistItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddWishlistItem: %w", err)
	}
	if q.checkReviewExistsStmt, err = db.PrepareContext(ctx, checkReviewExists); err != nil {
		return nil, fmt.Errorf("error preparing query CheckReviewExists: %w", err)
	}
	if q.checkUserPurchasedProductStmt, err = db.PrepareContext(ctx, checkUserPurchasedProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CheckUserPurchasedProduct: %w", err)
	}
	if q.checkWishlistItemExistsStmt, err = db.PrepareContext(ctx, checkWishlistItemExists); err != nil {
		return nil, fmt.Errorf("error preparing query CheckWishlistItemExists: %w", err)
	}
	if q.countCartItemsStmt, err = db.PrepareContext(ctx, countCartItems); err != nil {
		return nil, fmt.Errorf("error preparing query CountCartItems: %w", err)
	}
	if q.countReviewsByProductIDStmt, err = db.PrepareContext(ctx, countReviewsByProductID); err != nil {
		return nil, fmt.Errorf("error preparing query CountReviewsByProductID: %w", err)
	}
	if q.countReviewsByUserIDStmt, err = db.PrepareContext(ctx, countReviewsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query CountReviewsByUserID: %w", err)
	}
	if q.createAddressStmt, err = db.PrepareContext(ctx, createAddress); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAddress: %w", err)
	}
	if q.createBrandStmt, err = db.PrepareContext(ctx, createBrand); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBrand: %w", err)
	}
	if q.createCartStmt, err = db.PrepareContext(ctx, createCart); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCart: %w", err)
	}
	if q.createCategoryStmt, err = db.PrepareContext(ctx, createCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCategory: %w", err)
	}
	if q.createOrderStmt, err = db.PrepareContext(ctx, createOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrder: %w", err)
	}
	if q.createOrderItemStmt, err = db.PrepareContext(ctx, createOrderItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrderItem: %w", err)
	}
	if q.createOutboxEventStmt, err = db.PrepareContext(ctx, createOutboxEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOutboxEvent: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createReviewStmt, err = db.PrepareContext(ctx, createReview); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReview: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.decrementCartItemQtyStmt, err = db.PrepareContext(ctx, decrementCartItemQty); err != nil {
		return nil, fmt.Errorf("error preparing query DecrementCartItemQty: %w", err)
	}
	if q.deleteAllCartItemsStmt, err = db.PrepareContext(ctx, deleteAllCartItems); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllCartItems: %w", err)
	}
	if q.deleteCartStmt, err = db.PrepareContext(ctx, deleteCart); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCart: %w", err)
	}
	if q.deleteCartItemStmt, err = db.PrepareContext(ctx, deleteCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCartItem: %w", err)
	}
	if q.deleteReviewStmt, err = db.PrepareContext(ctx, deleteReview); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteReview: %w", err)
	}
	if q.deleteWishlistItemStmt, err = db.PrepareContext(ctx, deleteWishlistItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWishlistItem: %w", err)
	}
	if q.getAddressByIDStmt, err = db.PrepareContext(ctx, getAddressByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddressByID: %w", err)
	}
	if q.getAverageRatingByProductIDStmt, err = db.PrepareContext(ctx, getAverageRatingByProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageRatingByProductID: %w", err)
	}
	if q.getBrandByIDStmt, err = db.PrepareContext(ctx, getBrandByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBrandByID: %w", err)
	}
	if q.getBrandBySlugStmt, err = db.PrepareContext(ctx, getBrandBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetBrandBySlug: %w", err)
	}
	if q.getCartByUserIDStmt, err = db.PrepareContext(ctx, getCartByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartByUserID: %w", err)
	}
	if q.getCartDetailStmt, err = db.PrepareContext(ctx, getCartDetail); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartDetail: %w", err)
	}
	if q.getCartItemByCartAndProductStmt, err = db.PrepareContext(ctx, getCartItemByCartAndProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartItemByCartAndProduct: %w", err)
	}
	if q.getCategoryByIDStmt, err = db.PrepareContext(ctx, getCategoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryByID: %w", err)
	}
	if q.getCategoryBySlugStmt, err = db.PrepareContext(ctx, getCategoryBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryBySlug: %w", err)
	}
	if q.getCompletedOrderForReviewStmt, err = db.PrepareContext(ctx, getCompletedOrderForReview); err != nil {
		return nil, fmt.Errorf("error preparing query GetCompletedOrderForReview: %w", err)
	}
	if q.getIDsBySlugsStmt, err = db.PrepareContext(ctx, getIDsBySlugs); err != nil {
		return nil, fmt.Errorf("error preparing query GetIDsBySlugs: %w", err)
	}
	if q.getOrCreateWishlistStmt, err = db.PrepareContext(ctx, getOrCreateWishlist); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrCreateWishlist: %w", err)
	}
	if q.getOrderByIDStmt, err = db.PrepareContext(ctx, getOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderByID: %w", err)
	}
	if q.getOrderItemsStmt, err = db.PrepareContext(ctx, getOrderItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItems: %w", err)
	}
	if q.getOrderPaymentForUpdateByIDStmt, err = db.PrepareContext(ctx, getOrderPaymentForUpdateByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderPaymentForUpdateByID: %w", err)
	}
	if q.getOrderPaymentForUpdateByOrderNumberStmt, err = db.PrepareContext(ctx, getOrderPaymentForUpdateByOrderNumber); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderPaymentForUpdateByOrderNumber: %w", err)
	}
	if q.getOrderSummaryByOrderNumberStmt, err = db.PrepareContext(ctx, getOrderSummaryByOrderNumber); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderSummaryByOrderNumber: %w", err)
	}
	if q.getProductByIDStmt, err = db.PrepareContext(ctx, getProductByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductByID: %w", err)
	}
	if q.getProductBySlugStmt, err = db.PrepareContext(ctx, getProductBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductBySlug: %w", err)
	}
	if q.getReviewByIDStmt, err = db.PrepareContext(ctx, getReviewByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReviewByID: %w", err)
	}
	if q.getReviewsByProductIDStmt, err = db.PrepareContext(ctx, getReviewsByProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReviewsByProductID: %w", err)
	}
	if q.getReviewsByUserIDStmt, err = db.PrepareContext(ctx, getReviewsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetReviewsByUserID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserRatingBreakdownStmt, err = db.PrepareContext(ctx, getUserRatingBreakdown); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserRatingBreakdown: %w", err)
	}
	if q.getWishlistByUserIDStmt, err = db.PrepareContext(ctx, getWishlistByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetWishlistByUserID: %w", err)
	}
	if q.getWishlistItemsStmt, err = db.PrepareContext(ctx, getWishlistItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetWishlistItems: %w", err)
	}
	if q.getWishlistWithItemsStmt, err = db.PrepareContext(ctx, getWishlistWithItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetWishlistWithItems: %w", err)
	}
	if q.incrementCartItemQtyStmt, err = db.PrepareContext(ctx, incrementCartItemQty); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementCartItemQty: %w", err)
	}
	if q.listAddressesAdminStmt, err = db.PrepareContext(ctx, listAddressesAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query ListAddressesAdmin: %w", err)
	}
	if q.listAddressesByUserStmt, err = db.PrepareContext(ctx, listAddressesByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListAddressesByUser: %w", err)
	}
	if q.listBrandsAdminStmt, err = db.PrepareContext(ctx, listBrandsAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query ListBrandsAdmin: %w", err)
	}
	if q.listBrandsPublicStmt, err = db.PrepareContext(ctx, listBrandsPublic); err != nil {
		return nil, fmt.Errorf("error preparing query ListBrandsPublic: %w", err)
	}
	if q.listCategoriesAdminStmt, err = db.PrepareContext(ctx, listCategoriesAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategoriesAdmin: %w", err)
	}
	if q.listCategoriesPublicStmt, err = db.PrepareContext(ctx, listCategoriesPublic); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategoriesPublic: %w", err)
	}
	if q.listOrdersStmt, err = db.PrepareContext(ctx, listOrders); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrders: %w", err)
	}
	if q.listOrdersAdminStmt, err = db.PrepareContext(ctx, listOrdersAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrdersAdmin: %w", err)
	}
	if q.listPendingOutboxStmt, err = db.PrepareContext(ctx, listPendingOutbox); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingOutbox: %w", err)
	}
	if q.listProductsAdminStmt, err = db.PrepareContext(ctx, listProductsAdmin); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsAdmin: %w", err)
	}
	if q.listProductsForInternalStmt, err = db.PrepareContext(ctx, listProductsForInternal); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsForInternal: %w", err)
	}
	if q.listProductsPublicStmt, err = db.PrepareContext(ctx, listProductsPublic); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsPublic: %w", err)
	}
	if q.markOutboxEventFailedStmt, err = db.PrepareContext(ctx, markOutboxEventFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkOutboxEventFailed: %w", err)
	}
	if q.markOutboxEventSentStmt, err = db.PrepareContext(ctx, markOutboxEventSent); err != nil {
		return nil, fmt.Errorf("error preparing query MarkOutboxEventSent: %w", err)
	}
	if q.restoreBrandStmt, err = db.PrepareContext(ctx, restoreBrand); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreBrand: %w", err)
	}
	if q.restoreCategoryStmt, err = db.PrepareContext(ctx, restoreCategory); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreCategory: %w", err)
	}
	if q.restoreProductStmt, err = db.PrepareContext(ctx, restoreProduct); err != nil {
		return nil, fmt.Errorf("error preparing query RestoreProduct: %w", err)
	}
	if q.softDeleteAddressStmt, err = db.PrepareContext(ctx, softDeleteAddress); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteAddress: %w", err)
	}
	if q.softDeleteBrandStmt, err = db.PrepareContext(ctx, softDeleteBrand); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteBrand: %w", err)
	}
	if q.softDeleteCategoryStmt, err = db.PrepareContext(ctx, softDeleteCategory); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteCategory: %w", err)
	}
	if q.softDeleteProductStmt, err = db.PrepareContext(ctx, softDeleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteProduct: %w", err)
	}
	if q.unsetPrimaryAddressByUserStmt, err = db.PrepareContext(ctx, unsetPrimaryAddressByUser); err != nil {
		return nil, fmt.Errorf("error preparing query UnsetPrimaryAddressByUser: %w", err)
	}
	if q.updateAddressStmt, err = db.PrepareContext(ctx, updateAddress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAddress: %w", err)
	}
	if q.updateBrandStmt, err = db.PrepareContext(ctx, updateBrand); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBrand: %w", err)
	}
	if q.updateCartItemQtyStmt, err = db.PrepareContext(ctx, updateCartItemQty); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCartItemQty: %w", err)
	}
	if q.updateCategoryStmt, err = db.PrepareContext(ctx, updateCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCategory: %w", err)
	}
	if q.updateCustomerPasswordStmt, err = db.PrepareContext(ctx, updateCustomerPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCustomerPassword: %w", err)
	}
	if q.updateCustomerProfileStmt, err = db.PrepareContext(ctx, updateCustomerProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCustomerProfile: %w", err)
	}
	if q.updateOrderPaymentStatusStmt, err = db.PrepareContext(ctx, updateOrderPaymentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderPaymentStatus: %w", err)
	}
	if q.updateOrderSnapTokenStmt, err = db.PrepareContext(ctx, updateOrderSnapToken); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderSnapToken: %w", err)
	}
	if q.updateOrderStatusStmt, err = db.PrepareContext(ctx, updateOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderStatus: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	if q.updateReviewStmt, err = db.PrepareContext(ctx, updateReview); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateReview: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCartItemStmt != nil {
		if cerr := q.addCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCartItemStmt: %w", cerr)
		}
	}
	if q.addWishlistItemStmt != nil {
		if cerr := q.addWishlistItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addWishlistItemStmt: %w", cerr)
		}
	}
	if q.checkReviewExistsStmt != nil {
		if cerr := q.checkReviewExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkReviewExistsStmt: %w", cerr)
		}
	}
	if q.checkUserPurchasedProductStmt != nil {
		if cerr := q.checkUserPurchasedProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkUserPurchasedProductStmt: %w", cerr)
		}
	}
	if q.checkWishlistItemExistsStmt != nil {
		if cerr := q.checkWishlistItemExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkWishlistItemExistsStmt: %w", cerr)
		}
	}
	if q.countCartItemsStmt != nil {
		if cerr := q.countCartItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCartItemsStmt: %w", cerr)
		}
	}
	if q.countReviewsByProductIDStmt != nil {
		if cerr := q.countReviewsByProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countReviewsByProductIDStmt: %w", cerr)
		}
	}
	if q.countReviewsByUserIDStmt != nil {
		if cerr := q.countReviewsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countReviewsByUserIDStmt: %w", cerr)
		}
	}
	if q.createAddressStmt != nil {
		if cerr := q.createAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAddressStmt: %w", cerr)
		}
	}
	if q.createBrandStmt != nil {
		if cerr := q.createBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBrandStmt: %w", cerr)
		}
	}
	if q.createCartStmt != nil {
		if cerr := q.createCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCartStmt: %w", cerr)
		}
	}
	if q.createCategoryStmt != nil {
		if cerr := q.createCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCategoryStmt: %w", cerr)
		}
	}
	if q.createOrderStmt != nil {
		if cerr := q.createOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderStmt: %w", cerr)
		}
	}
	if q.createOrderItemStmt != nil {
		if cerr := q.createOrderItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderItemStmt: %w", cerr)
		}
	}
	if q.createOutboxEventStmt != nil {
		if cerr := q.createOutboxEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOutboxEventStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createReviewStmt != nil {
		if cerr := q.createReviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReviewStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.decrementCartItemQtyStmt != nil {
		if cerr := q.decrementCartItemQtyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing decrementCartItemQtyStmt: %w", cerr)
		}
	}
	if q.deleteAllCartItemsStmt != nil {
		if cerr := q.deleteAllCartItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllCartItemsStmt: %w", cerr)
		}
	}
	if q.deleteCartStmt != nil {
		if cerr := q.deleteCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartStmt: %w", cerr)
		}
	}
	if q.deleteCartItemStmt != nil {
		if cerr := q.deleteCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCartItemStmt: %w", cerr)
		}
	}
	if q.deleteReviewStmt != nil {
		if cerr := q.deleteReviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteReviewStmt: %w", cerr)
		}
	}
	if q.deleteWishlistItemStmt != nil {
		if cerr := q.deleteWishlistItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWishlistItemStmt: %w", cerr)
		}
	}
	if q.getAddressByIDStmt != nil {
		if cerr := q.getAddressByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressByIDStmt: %w", cerr)
		}
	}
	if q.getAverageRatingByProductIDStmt != nil {
		if cerr := q.getAverageRatingByProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageRatingByProductIDStmt: %w", cerr)
		}
	}
	if q.getBrandByIDStmt != nil {
		if cerr := q.getBrandByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBrandByIDStmt: %w", cerr)
		}
	}
	if q.getBrandBySlugStmt != nil {
		if cerr := q.getBrandBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBrandBySlugStmt: %w", cerr)
		}
	}
	if q.getCartByUserIDStmt != nil {
		if cerr := q.getCartByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartByUserIDStmt: %w", cerr)
		}
	}
	if q.getCartDetailStmt != nil {
		if cerr := q.getCartDetailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartDetailStmt: %w", cerr)
		}
	}
	if q.getCartItemByCartAndProductStmt != nil {
		if cerr := q.getCartItemByCartAndProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartItemByCartAndProductStmt: %w", cerr)
		}
	}
	if q.getCategoryByIDStmt != nil {
		if cerr := q.getCategoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryByIDStmt: %w", cerr)
		}
	}
	if q.getCategoryBySlugStmt != nil {
		if cerr := q.getCategoryBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryBySlugStmt: %w", cerr)
		}
	}
	if q.getCompletedOrderForReviewStmt != nil {
		if cerr := q.getCompletedOrderForReviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCompletedOrderForReviewStmt: %w", cerr)
		}
	}
	if q.getIDsBySlugsStmt != nil {
		if cerr := q.getIDsBySlugsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIDsBySlugsStmt: %w", cerr)
		}
	}
	if q.getOrCreateWishlistStmt != nil {
		if cerr := q.getOrCreateWishlistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrCreateWishlistStmt: %w", cerr)
		}
	}
	if q.getOrderByIDStmt != nil {
		if cerr := q.getOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderByIDStmt: %w", cerr)
		}
	}
	if q.getOrderItemsStmt != nil {
		if cerr := q.getOrderItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsStmt: %w", cerr)
		}
	}
	if q.getOrderPaymentForUpdateByIDStmt != nil {
		if cerr := q.getOrderPaymentForUpdateByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderPaymentForUpdateByIDStmt: %w", cerr)
		}
	}
	if q.getOrderPaymentForUpdateByOrderNumberStmt != nil {
		if cerr := q.getOrderPaymentForUpdateByOrderNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderPaymentForUpdateByOrderNumberStmt: %w", cerr)
		}
	}
	if q.getOrderSummaryByOrderNumberStmt != nil {
		if cerr := q.getOrderSummaryByOrderNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderSummaryByOrderNumberStmt: %w", cerr)
		}
	}
	if q.getProductByIDStmt != nil {
		if cerr := q.getProductByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductByIDStmt: %w", cerr)
		}
	}
	if q.getProductBySlugStmt != nil {
		if cerr := q.getProductBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductBySlugStmt: %w", cerr)
		}
	}
	if q.getReviewByIDStmt != nil {
		if cerr := q.getReviewByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReviewByIDStmt: %w", cerr)
		}
	}
	if q.getReviewsByProductIDStmt != nil {
		if cerr := q.getReviewsByProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReviewsByProductIDStmt: %w", cerr)
		}
	}
	if q.getReviewsByUserIDStmt != nil {
		if cerr := q.getReviewsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getReviewsByUserIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserRatingBreakdownStmt != nil {
		if cerr := q.getUserRatingBreakdownStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserRatingBreakdownStmt: %w", cerr)
		}
	}
	if q.getWishlistByUserIDStmt != nil {
		if cerr := q.getWishlistByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWishlistByUserIDStmt: %w", cerr)
		}
	}
	if q.getWishlistItemsStmt != nil {
		if cerr := q.getWishlistItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWishlistItemsStmt: %w", cerr)
		}
	}
	if q.getWishlistWithItemsStmt != nil {
		if cerr := q.getWishlistWithItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWishlistWithItemsStmt: %w", cerr)
		}
	}
	if q.incrementCartItemQtyStmt != nil {
		if cerr := q.incrementCartItemQtyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementCartItemQtyStmt: %w", cerr)
		}
	}
	if q.listAddressesAdminStmt != nil {
		if cerr := q.listAddressesAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAddressesAdminStmt: %w", cerr)
		}
	}
	if q.listAddressesByUserStmt != nil {
		if cerr := q.listAddressesByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAddressesByUserStmt: %w", cerr)
		}
	}
	if q.listBrandsAdminStmt != nil {
		if cerr := q.listBrandsAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBrandsAdminStmt: %w", cerr)
		}
	}
	if q.listBrandsPublicStmt != nil {
		if cerr := q.listBrandsPublicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBrandsPublicStmt: %w", cerr)
		}
	}
	if q.listCategoriesAdminStmt != nil {
		if cerr := q.listCategoriesAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoriesAdminStmt: %w", cerr)
		}
	}
	if q.listCategoriesPublicStmt != nil {
		if cerr := q.listCategoriesPublicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoriesPublicStmt: %w", cerr)
		}
	}
	if q.listOrdersStmt != nil {
		if cerr := q.listOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrdersStmt: %w", cerr)
		}
	}
	if q.listOrdersAdminStmt != nil {
		if cerr := q.listOrdersAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrdersAdminStmt: %w", cerr)
		}
	}
	if q.listPendingOutboxStmt != nil {
		if cerr := q.listPendingOutboxStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingOutboxStmt: %w", cerr)
		}
	}
	if q.listProductsAdminStmt != nil {
		if cerr := q.listProductsAdminStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsAdminStmt: %w", cerr)
		}
	}
	if q.listProductsForInternalStmt != nil {
		if cerr := q.listProductsForInternalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsForInternalStmt: %w", cerr)
		}
	}
	if q.listProductsPublicStmt != nil {
		if cerr := q.listProductsPublicStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsPublicStmt: %w", cerr)
		}
	}
	if q.markOutboxEventFailedStmt != nil {
		if cerr := q.markOutboxEventFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markOutboxEventFailedStmt: %w", cerr)
		}
	}
	if q.markOutboxEventSentStmt != nil {
		if cerr := q.markOutboxEventSentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markOutboxEventSentStmt: %w", cerr)
		}
	}
	if q.restoreBrandStmt != nil {
		if cerr := q.restoreBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreBrandStmt: %w", cerr)
		}
	}
	if q.restoreCategoryStmt != nil {
		if cerr := q.restoreCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreCategoryStmt: %w", cerr)
		}
	}
	if q.restoreProductStmt != nil {
		if cerr := q.restoreProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing restoreProductStmt: %w", cerr)
		}
	}
	if q.softDeleteAddressStmt != nil {
		if cerr := q.softDeleteAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteAddressStmt: %w", cerr)
		}
	}
	if q.softDeleteBrandStmt != nil {
		if cerr := q.softDeleteBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteBrandStmt: %w", cerr)
		}
	}
	if q.softDeleteCategoryStmt != nil {
		if cerr := q.softDeleteCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteCategoryStmt: %w", cerr)
		}
	}
	if q.softDeleteProductStmt != nil {
		if cerr := q.softDeleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteProductStmt: %w", cerr)
		}
	}
	if q.unsetPrimaryAddressByUserStmt != nil {
		if cerr := q.unsetPrimaryAddressByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unsetPrimaryAddressByUserStmt: %w", cerr)
		}
	}
	if q.updateAddressStmt != nil {
		if cerr := q.updateAddressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAddressStmt: %w", cerr)
		}
	}
	if q.updateBrandStmt != nil {
		if cerr := q.updateBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBrandStmt: %w", cerr)
		}
	}
	if q.updateCartItemQtyStmt != nil {
		if cerr := q.updateCartItemQtyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartItemQtyStmt: %w", cerr)
		}
	}
	if q.updateCategoryStmt != nil {
		if cerr := q.updateCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCategoryStmt: %w", cerr)
		}
	}
	if q.updateCustomerPasswordStmt != nil {
		if cerr := q.updateCustomerPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCustomerPasswordStmt: %w", cerr)
		}
	}
	if q.updateCustomerProfileStmt != nil {
		if cerr := q.updateCustomerProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCustomerProfileStmt: %w", cerr)
		}
	}
	if q.updateOrderPaymentStatusStmt != nil {
		if cerr := q.updateOrderPaymentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderPaymentStatusStmt: %w", cerr)
		}
	}
	if q.updateOrderSnapTokenStmt != nil {
		if cerr := q.updateOrderSnapTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderSnapTokenStmt: %w", cerr)
		}
	}
	if q.updateOrderStatusStmt != nil {
		if cerr := q.updateOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderStatusStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	if q.updateReviewStmt != nil {
		if cerr := q.updateReviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateReviewStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                        DBTX
	tx                                        *sql.Tx
	addCartItemStmt                           *sql.Stmt
	addWishlistItemStmt                       *sql.Stmt
	checkReviewExistsStmt                     *sql.Stmt
	checkUserPurchasedProductStmt             *sql.Stmt
	checkWishlistItemExistsStmt               *sql.Stmt
	countCartItemsStmt                        *sql.Stmt
	countReviewsByProductIDStmt               *sql.Stmt
	countReviewsByUserIDStmt                  *sql.Stmt
	createAddressStmt                         *sql.Stmt
	createBrandStmt                           *sql.Stmt
	createCartStmt                            *sql.Stmt
	createCategoryStmt                        *sql.Stmt
	createOrderStmt                           *sql.Stmt
	createOrderItemStmt                       *sql.Stmt
	createOutboxEventStmt                     *sql.Stmt
	createProductStmt                         *sql.Stmt
	createReviewStmt                          *sql.Stmt
	createUserStmt                            *sql.Stmt
	decrementCartItemQtyStmt                  *sql.Stmt
	deleteAllCartItemsStmt                    *sql.Stmt
	deleteCartStmt                            *sql.Stmt
	deleteCartItemStmt                        *sql.Stmt
	deleteReviewStmt                          *sql.Stmt
	deleteWishlistItemStmt                    *sql.Stmt
	getAddressByIDStmt                        *sql.Stmt
	getAverageRatingByProductIDStmt           *sql.Stmt
	getBrandByIDStmt                          *sql.Stmt
	getBrandBySlugStmt                        *sql.Stmt
	getCartByUserIDStmt                       *sql.Stmt
	getCartDetailStmt                         *sql.Stmt
	getCartItemByCartAndProductStmt           *sql.Stmt
	getCategoryByIDStmt                       *sql.Stmt
	getCategoryBySlugStmt                     *sql.Stmt
	getCompletedOrderForReviewStmt            *sql.Stmt
	getIDsBySlugsStmt                         *sql.Stmt
	getOrCreateWishlistStmt                   *sql.Stmt
	getOrderByIDStmt                          *sql.Stmt
	getOrderItemsStmt                         *sql.Stmt
	getOrderPaymentForUpdateByIDStmt          *sql.Stmt
	getOrderPaymentForUpdateByOrderNumberStmt *sql.Stmt
	getOrderSummaryByOrderNumberStmt          *sql.Stmt
	getProductByIDStmt                        *sql.Stmt
	getProductBySlugStmt                      *sql.Stmt
	getReviewByIDStmt                         *sql.Stmt
	getReviewsByProductIDStmt                 *sql.Stmt
	getReviewsByUserIDStmt                    *sql.Stmt
	getUserByEmailStmt                        *sql.Stmt
	getUserByIDStmt                           *sql.Stmt
	getUserRatingBreakdownStmt                *sql.Stmt
	getWishlistByUserIDStmt                   *sql.Stmt
	getWishlistItemsStmt                      *sql.Stmt
	getWishlistWithItemsStmt                  *sql.Stmt
	incrementCartItemQtyStmt                  *sql.Stmt
	listAddressesAdminStmt                    *sql.Stmt
	listAddressesByUserStmt                   *sql.Stmt
	listBrandsAdminStmt                       *sql.Stmt
	listBrandsPublicStmt                      *sql.Stmt
	listCategoriesAdminStmt                   *sql.Stmt
	listCategoriesPublicStmt                  *sql.Stmt
	listOrdersStmt                            *sql.Stmt
	listOrdersAdminStmt                       *sql.Stmt
	listPendingOutboxStmt                     *sql.Stmt
	listProductsAdminStmt                     *sql.Stmt
	listProductsForInternalStmt               *sql.Stmt
	listProductsPublicStmt                    *sql.Stmt
	markOutboxEventFailedStmt                 *sql.Stmt
	markOutboxEventSentStmt                   *sql.Stmt
	restoreBrandStmt                          *sql.Stmt
	restoreCategoryStmt                       *sql.Stmt
	restoreProductStmt                        *sql.Stmt
	softDeleteAddressStmt                     *sql.Stmt
	softDeleteBrandStmt                       *sql.Stmt
	softDeleteCategoryStmt                    *sql.Stmt
	softDeleteProductStmt                     *sql.Stmt
	unsetPrimaryAddressByUserStmt             *sql.Stmt
	updateAddressStmt                         *sql.Stmt
	updateBrandStmt                           *sql.Stmt
	updateCartItemQtyStmt                     *sql.Stmt
	updateCategoryStmt                        *sql.Stmt
	updateCustomerPasswordStmt                *sql.Stmt
	updateCustomerProfileStmt                 *sql.Stmt
	updateOrderPaymentStatusStmt              *sql.Stmt
	updateOrderSnapTokenStmt                  *sql.Stmt
	updateOrderStatusStmt                     *sql.Stmt
	updateProductStmt                         *sql.Stmt
	updateReviewStmt                          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                        tx,
		tx:                                        tx,
		addCartItemStmt:                           q.addCartItemStmt,
		addWishlistItemStmt:                       q.addWishlistItemStmt,
		checkReviewExistsStmt:                     q.checkReviewExistsStmt,
		checkUserPurchasedProductStmt:             q.checkUserPurchasedProductStmt,
		checkWishlistItemExistsStmt:               q.checkWishlistItemExistsStmt,
		countCartItemsStmt:                        q.countCartItemsStmt,
		countReviewsByProductIDStmt:               q.countReviewsByProductIDStmt,
		countReviewsByUserIDStmt:                  q.countReviewsByUserIDStmt,
		createAddressStmt:                         q.createAddressStmt,
		createBrandStmt:                           q.createBrandStmt,
		createCartStmt:                            q.createCartStmt,
		createCategoryStmt:                        q.createCategoryStmt,
		createOrderStmt:                           q.createOrderStmt,
		createOrderItemStmt:                       q.createOrderItemStmt,
		createOutboxEventStmt:                     q.createOutboxEventStmt,
		createProductStmt:                         q.createProductStmt,
		createReviewStmt:                          q.createReviewStmt,
		createUserStmt:                            q.createUserStmt,
		decrementCartItemQtyStmt:                  q.decrementCartItemQtyStmt,
		deleteAllCartItemsStmt:                    q.deleteAllCartItemsStmt,
		deleteCartStmt:                            q.deleteCartStmt,
		deleteCartItemStmt:                        q.deleteCartItemStmt,
		deleteReviewStmt:                          q.deleteReviewStmt,
		deleteWishlistItemStmt:                    q.deleteWishlistItemStmt,
		getAddressByIDStmt:                        q.getAddressByIDStmt,
		getAverageRatingByProductIDStmt:           q.getAverageRatingByProductIDStmt,
		getBrandByIDStmt:                          q.getBrandByIDStmt,
		getBrandBySlugStmt:                        q.getBrandBySlugStmt,
		getCartByUserIDStmt:                       q.getCartByUserIDStmt,
		getCartDetailStmt:                         q.getCartDetailStmt,
		getCartItemByCartAndProductStmt:           q.getCartItemByCartAndProductStmt,
		getCategoryByIDStmt:                       q.getCategoryByIDStmt,
		getCategoryBySlugStmt:                     q.getCategoryBySlugStmt,
		getCompletedOrderForReviewStmt:            q.getCompletedOrderForReviewStmt,
		getIDsBySlugsStmt:                         q.getIDsBySlugsStmt,
		getOrCreateWishlistStmt:                   q.getOrCreateWishlistStmt,
		getOrderByIDStmt:                          q.getOrderByIDStmt,
		getOrderItemsStmt:                         q.getOrderItemsStmt,
		getOrderPaymentForUpdateByIDStmt:          q.getOrderPaymentForUpdateByIDStmt,
		getOrderPaymentForUpdateByOrderNumberStmt: q.getOrderPaymentForUpdateByOrderNumberStmt,
		getOrderSummaryByOrderNumberStmt:          q.getOrderSummaryByOrderNumberStmt,
		getProductByIDStmt:                        q.getProductByIDStmt,
		getProductBySlugStmt:                      q.getProductBySlugStmt,
		getReviewByIDStmt:                         q.getReviewByIDStmt,
		getReviewsByProductIDStmt:                 q.getReviewsByProductIDStmt,
		getReviewsByUserIDStmt:                    q.getReviewsByUserIDStmt,
		getUserByEmailStmt:                        q.getUserByEmailStmt,
		getUserByIDStmt:                           q.getUserByIDStmt,
		getUserRatingBreakdownStmt:                q.getUserRatingBreakdownStmt,
		getWishlistByUserIDStmt:                   q.getWishlistByUserIDStmt,
		getWishlistItemsStmt:                      q.getWishlistItemsStmt,
		getWishlistWithItemsStmt:                  q.getWishlistWithItemsStmt,
		incrementCartItemQtyStmt:                  q.incrementCartItemQtyStmt,
		listAddressesAdminStmt:                    q.listAddressesAdminStmt,
		listAddressesByUserStmt:                   q.listAddressesByUserStmt,
		listBrandsAdminStmt:                       q.listBrandsAdminStmt,
		listBrandsPublicStmt:                      q.listBrandsPublicStmt,
		listCategoriesAdminStmt:                   q.listCategoriesAdminStmt,
		listCategoriesPublicStmt:                  q.listCategoriesPublicStmt,
		listOrdersStmt:                            q.listOrdersStmt,
		listOrdersAdminStmt:                       q.listOrdersAdminStmt,
		listPendingOutboxStmt:                     q.listPendingOutboxStmt,
		listProductsAdminStmt:                     q.listProductsAdminStmt,
		listProductsForInternalStmt:               q.listProductsForInternalStmt,
		listProductsPublicStmt:                    q.listProductsPublicStmt,
		markOutboxEventFailedStmt:                 q.markOutboxEventFailedStmt,
		markOutboxEventSentStmt:                   q.markOutboxEventSentStmt,
		restoreBrandStmt:                          q.restoreBrandStmt,
		restoreCategoryStmt:                       q.restoreCategoryStmt,
		restoreProductStmt:                        q.restoreProductStmt,
		softDeleteAddressStmt:                     q.softDeleteAddressStmt,
		softDeleteBrandStmt:                       q.softDeleteBrandStmt,
		softDeleteCategoryStmt:                    q.softDeleteCategoryStmt,
		softDeleteProductStmt:                     q.softDeleteProductStmt,
		unsetPrimaryAddressByUserStmt:             q.unsetPrimaryAddressByUserStmt,
		updateAddressStmt:                         q.updateAddressStmt,
		updateBrandStmt:                           q.updateBrandStmt,
		updateCartItemQtyStmt:                     q.updateCartItemQtyStmt,
		updateCategoryStmt:                        q.updateCategoryStmt,
		updateCustomerPasswordStmt:                q.updateCustomerPasswordStmt,
		updateCustomerProfileStmt:                 q.updateCustomerProfileStmt,
		updateOrderPaymentStatusStmt:              q.updateOrderPaymentStatusStmt,
		updateOrderSnapTokenStmt:                  q.updateOrderSnapTokenStmt,
		updateOrderStatusStmt:                     q.updateOrderStatusStmt,
		updateProductStmt:                         q.updateProductStmt,
		updateReviewStmt:                          q.updateReviewStmt,
	}
}
