// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (
  id, aggregate_type, aggregate_id, event_type, payload, status
) VALUES ($1, $2, $3, $4, $5, 'PENDING')
`

type CreateOutboxEventParams struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.exec(ctx, q.createOutboxEventStmt, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listPendingOutbox = `-- name: ListPendingOutbox :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, status, created_at, processed_at FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingOutbox(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.query(ctx, q.listPendingOutboxStmt, listPendingOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE outbox_events
SET status = 'SENT', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.markOutboxSentStmt, markOutboxSent, id)
	return err
}

const updateOutboxEventStatus = `-- name: UpdateOutboxEventStatus :exec
UPDATE outbox_events 
SET status = $2, updated_at = NOW() 
WHERE id = $1
`

type UpdateOutboxEventStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOutboxEventStatus(ctx context.Context, arg UpdateOutboxEventStatusParams) error {
	_, err := q.exec(ctx, q.updateOutboxEventStatusStmt, updateOutboxEventStatus, arg.ID, arg.Status)
	return err
}
