// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (brand_id, category_id, name, slug, description, price, stock, sku, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category_id, name, slug, description, price, stock, sku, image_url, is_active, created_at, updated_at, deleted_at, discount_price, brand_id
`

type CreateProductParams struct {
	BrandID     uuid.NullUUID  `json:"brand_id"`
	CategoryID  uuid.UUID      `json:"category_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Sku         sql.NullString `json:"sku"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Sku,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DiscountPrice,
		&i.BrandID,
	)
	return i, err
}

const getIDsBySlugs = `-- name: GetIDsBySlugs :many
SELECT id
FROM categories
WHERE slug = ANY($1::text[])
AND deleted_at IS NULL
`

func (q *Queries) GetIDsBySlugs(ctx context.Context, dollar_1 []string) ([]uuid.UUID, error) {
	rows, err := q.query(ctx, q.getIDsBySlugsStmt, getIDsBySlugs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, p.discount_price, p.brand_id, c.name as category_name 
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.id = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	Price         string         `json:"price"`
	Stock         int32          `json:"stock"`
	Sku           sql.NullString `json:"sku"`
	ImageUrl      sql.NullString `json:"image_url"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DiscountPrice sql.NullString `json:"discount_price"`
	BrandID       uuid.NullUUID  `json:"brand_id"`
	CategoryName  string         `json:"category_name"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.queryRow(ctx, q.getProductByIDStmt, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DiscountPrice,
		&i.BrandID,
		&i.CategoryName,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, p.discount_price, p.brand_id, c.name as category_name 
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.slug = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductBySlugRow struct {
	ID            uuid.UUID      `json:"id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	Price         string         `json:"price"`
	Stock         int32          `json:"stock"`
	Sku           sql.NullString `json:"sku"`
	ImageUrl      sql.NullString `json:"image_url"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DiscountPrice sql.NullString `json:"discount_price"`
	BrandID       uuid.NullUUID  `json:"brand_id"`
	CategoryName  string         `json:"category_name"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.queryRow(ctx, q.getProductBySlugStmt, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DiscountPrice,
		&i.BrandID,
		&i.CategoryName,
	)
	return i, err
}

const listProductsAdmin = `-- name: ListProductsAdmin :many
SELECT
    p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, p.discount_price, p.brand_id,
    c.id AS category_id,
    c.name AS category_name,
    b.id AS brand_id,
    b.name AS brand_name,
    COUNT(*) OVER() AS total_count
FROM products p
JOIN categories c ON p.category_id = c.id
LEFT JOIN brands b ON p.brand_id = b.id
WHERE
    p.deleted_at IS NULL
    AND ($3::uuid IS NULL OR p.brand_id = $3::uuid)
    AND ($4::uuid IS NULL OR p.category_id = $4::uuid)
    AND (
        $5::text IS NULL
        OR p.name ILIKE '%' || $5::text || '%'
        OR p.sku  ILIKE '%' || $5::text || '%'
    )
ORDER BY
    -- brand_name
    CASE
        WHEN $6 = 'brand_name' AND $7 = 'asc'
            THEN b.name
    END ASC,
    CASE
        WHEN $6 = 'brand_name' AND $7 = 'desc'
            THEN b.name
    END DESC,

    -- name
    CASE
        WHEN $6 = 'name' AND $7 = 'asc'
            THEN p.name
    END ASC,
    CASE
        WHEN $6 = 'name' AND $7 = 'desc'
            THEN p.name
    END DESC,

    -- stock
    CASE
        WHEN $6 = 'stock' AND $7 = 'asc'
            THEN p.stock
    END ASC,
    CASE
        WHEN $6 = 'stock' AND $7 = 'desc'
            THEN p.stock
    END DESC,

    -- price
    CASE
        WHEN $6 = 'price' AND $7 = 'asc'
            THEN p.price
    END ASC,
    CASE
        WHEN $6 = 'price' AND $7 = 'desc'
            THEN p.price
    END DESC,

    -- fallback (default)
    p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsAdminParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	BrandID    uuid.NullUUID  `json:"brand_id"`
	CategoryID uuid.NullUUID  `json:"category_id"`
	Search     sql.NullString `json:"search"`
	SortCol    interface{}    `json:"sort_col"`
	SortDir    interface{}    `json:"sort_dir"`
}

type ListProductsAdminRow struct {
	ID            uuid.UUID      `json:"id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	Price         string         `json:"price"`
	Stock         int32          `json:"stock"`
	Sku           sql.NullString `json:"sku"`
	ImageUrl      sql.NullString `json:"image_url"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DiscountPrice sql.NullString `json:"discount_price"`
	BrandID       uuid.NullUUID  `json:"brand_id"`
	CategoryID_2  uuid.UUID      `json:"category_id_2"`
	CategoryName  string         `json:"category_name"`
	BrandID_2     uuid.NullUUID  `json:"brand_id_2"`
	BrandName     sql.NullString `json:"brand_name"`
	TotalCount    int64          `json:"total_count"`
}

func (q *Queries) ListProductsAdmin(ctx context.Context, arg ListProductsAdminParams) ([]ListProductsAdminRow, error) {
	rows, err := q.query(ctx, q.listProductsAdminStmt, listProductsAdmin,
		arg.Limit,
		arg.Offset,
		arg.BrandID,
		arg.CategoryID,
		arg.Search,
		arg.SortCol,
		arg.SortDir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsAdminRow
	for rows.Next() {
		var i ListProductsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiscountPrice,
			&i.BrandID,
			&i.CategoryID_2,
			&i.CategoryName,
			&i.BrandID_2,
			&i.BrandName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForInternal = `-- name: ListProductsForInternal :many
SELECT id, name, price
FROM products
WHERE deleted_at IS NULL
  AND is_active = true
`

type ListProductsForInternalRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Price string    `json:"price"`
}

func (q *Queries) ListProductsForInternal(ctx context.Context) ([]ListProductsForInternalRow, error) {
	rows, err := q.query(ctx, q.listProductsForInternalStmt, listProductsForInternal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsForInternalRow
	for rows.Next() {
		var i ListProductsForInternalRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPublic = `-- name: ListProductsPublic :many
SELECT 
  p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, p.discount_price, p.brand_id, 
  c.name AS category_name,
  count(*) OVER() AS total_count
FROM products p
JOIN categories c ON p.category_id = c.id
LEFT JOIN brands b ON p.brand_id = b.id
WHERE 
  p.deleted_at IS NULL
  AND p.is_active = true
  
  -- Perbaikan filter kategori
  AND (
    COALESCE(cardinality($3::uuid[]), 0) = 0
    OR p.category_id = ANY($3::uuid[])
  )

  AND (
    $4::text IS NULL
    OR p.name ILIKE '%' || $4::text || '%'
  )

  AND (
    $5::text IS NULL
    OR b.slug = $5::text
  )

  -- Pastikan casting aman
  AND p.price >= $6::numeric
  AND p.price <= $7::numeric

ORDER BY 
  CASE WHEN LOWER($8::text) = 'newest' THEN p.created_at END DESC,
  CASE WHEN LOWER($8::text) = 'oldest' THEN p.created_at END ASC,
  CASE WHEN LOWER($8::text) = 'price_high' THEN p.price END DESC,
  CASE WHEN LOWER($8::text) = 'price_low' THEN p.price END ASC,
  p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsPublicParams struct {
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
	CategoryIds []uuid.UUID    `json:"category_ids"`
	Search      sql.NullString `json:"search"`
	BrandSlug   sql.NullString `json:"brand_slug"`
	MinPrice    string         `json:"min_price"`
	MaxPrice    string         `json:"max_price"`
	SortBy      string         `json:"sort_by"`
}

type ListProductsPublicRow struct {
	ID            uuid.UUID      `json:"id"`
	CategoryID    uuid.UUID      `json:"category_id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	Price         string         `json:"price"`
	Stock         int32          `json:"stock"`
	Sku           sql.NullString `json:"sku"`
	ImageUrl      sql.NullString `json:"image_url"`
	IsActive      sql.NullBool   `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DiscountPrice sql.NullString `json:"discount_price"`
	BrandID       uuid.NullUUID  `json:"brand_id"`
	CategoryName  string         `json:"category_name"`
	TotalCount    int64          `json:"total_count"`
}

func (q *Queries) ListProductsPublic(ctx context.Context, arg ListProductsPublicParams) ([]ListProductsPublicRow, error) {
	rows, err := q.query(ctx, q.listProductsPublicStmt, listProductsPublic,
		arg.Limit,
		arg.Offset,
		pq.Array(arg.CategoryIds),
		arg.Search,
		arg.BrandSlug,
		arg.MinPrice,
		arg.MaxPrice,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsPublicRow
	for rows.Next() {
		var i ListProductsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DiscountPrice,
			&i.BrandID,
			&i.CategoryName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProduct = `-- name: RestoreProduct :one
UPDATE products SET deleted_at = NULL WHERE id = $1 RETURNING id, category_id, name, slug, description, price, stock, sku, image_url, is_active, created_at, updated_at, deleted_at, discount_price, brand_id
`

func (q *Queries) RestoreProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.queryRow(ctx, q.restoreProductStmt, restoreProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DiscountPrice,
		&i.BrandID,
	)
	return i, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.softDeleteProductStmt, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    brand_id = $2,
    category_id = $3,
    name = $4,
    description = $5,
    price = $6,
    stock = $7,
    sku = $8,
    image_url = $9,
    is_active = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, name, slug, description, price, stock, sku, image_url, is_active, created_at, updated_at, deleted_at, discount_price, brand_id
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	BrandID     uuid.NullUUID  `json:"brand_id"`
	CategoryID  uuid.UUID      `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Sku         sql.NullString `json:"sku"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStmt, updateProduct,
		arg.ID,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Sku,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DiscountPrice,
		&i.BrandID,
	)
	return i, err
}
