// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishlists.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addWishlistItem = `-- name: AddWishlistItem :exec
INSERT INTO wishlist_items (wishlist_id, product_id)
VALUES ($1, $2)
ON CONFLICT (wishlist_id, product_id) DO NOTHING
`

type AddWishlistItemParams struct {
	WishlistID uuid.UUID `json:"wishlist_id"`
	ProductID  uuid.UUID `json:"product_id"`
}

func (q *Queries) AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) error {
	_, err := q.exec(ctx, q.addWishlistItemStmt, addWishlistItem, arg.WishlistID, arg.ProductID)
	return err
}

const checkWishlistItemExists = `-- name: CheckWishlistItemExists :one
SELECT EXISTS(
    SELECT 1 FROM wishlist_items
    WHERE wishlist_id = $1 AND product_id = $2
) AS exists
`

type CheckWishlistItemExistsParams struct {
	WishlistID uuid.UUID `json:"wishlist_id"`
	ProductID  uuid.UUID `json:"product_id"`
}

func (q *Queries) CheckWishlistItemExists(ctx context.Context, arg CheckWishlistItemExistsParams) (bool, error) {
	row := q.queryRow(ctx, q.checkWishlistItemExistsStmt, checkWishlistItemExists, arg.WishlistID, arg.ProductID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :exec
DELETE FROM wishlist_items
WHERE wishlist_id = $1 AND product_id = $2
`

type DeleteWishlistItemParams struct {
	WishlistID uuid.UUID `json:"wishlist_id"`
	ProductID  uuid.UUID `json:"product_id"`
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) error {
	_, err := q.exec(ctx, q.deleteWishlistItemStmt, deleteWishlistItem, arg.WishlistID, arg.ProductID)
	return err
}

const getOrCreateWishlist = `-- name: GetOrCreateWishlist :one
INSERT INTO wishlists (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) GetOrCreateWishlist(ctx context.Context, userID uuid.UUID) (Wishlist, error) {
	row := q.queryRow(ctx, q.getOrCreateWishlistStmt, getOrCreateWishlist, userID)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWishlistByUserID = `-- name: GetWishlistByUserID :one
SELECT id, user_id, created_at, updated_at FROM wishlists WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWishlistByUserID(ctx context.Context, userID uuid.UUID) (Wishlist, error) {
	row := q.queryRow(ctx, q.getWishlistByUserIDStmt, getWishlistByUserID, userID)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWishlistItems = `-- name: GetWishlistItems :many
SELECT wi.id, wi.wishlist_id, wi.product_id, wi.created_at, wi.updated_at, p.name, p.price, p.stock, p.image_url
FROM wishlist_items wi
JOIN products p ON wi.product_id = p.id
WHERE wi.wishlist_id = $1
ORDER BY wi.created_at DESC
`

type GetWishlistItemsRow struct {
	ID         uuid.UUID      `json:"id"`
	WishlistID uuid.UUID      `json:"wishlist_id"`
	ProductID  uuid.UUID      `json:"product_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	Name       string         `json:"name"`
	Price      string         `json:"price"`
	Stock      int32          `json:"stock"`
	ImageUrl   sql.NullString `json:"image_url"`
}

func (q *Queries) GetWishlistItems(ctx context.Context, wishlistID uuid.UUID) ([]GetWishlistItemsRow, error) {
	rows, err := q.query(ctx, q.getWishlistItemsStmt, getWishlistItems, wishlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWishlistItemsRow
	for rows.Next() {
		var i GetWishlistItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.WishlistID,
			&i.ProductID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
