// Code generated by MockGen. DO NOT EDIT.
// Source: wishlist_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dbgen "gadget-api/internal/dbgen"
	wishlist "gadget-api/internal/wishlist"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockRepository) AddItem(ctx context.Context, wishlistID, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, wishlistID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockRepositoryMockRecorder) AddItem(ctx, wishlistID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockRepository)(nil).AddItem), ctx, wishlistID, productID)
}

// CheckItemExists mocks base method.
func (m *MockRepository) CheckItemExists(ctx context.Context, wishlistID, productID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckItemExists", ctx, wishlistID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckItemExists indicates an expected call of CheckItemExists.
func (mr *MockRepositoryMockRecorder) CheckItemExists(ctx, wishlistID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckItemExists", reflect.TypeOf((*MockRepository)(nil).CheckItemExists), ctx, wishlistID, productID)
}

// DeleteItem mocks base method.
func (m *MockRepository) DeleteItem(ctx context.Context, wishlistID, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, wishlistID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockRepositoryMockRecorder) DeleteItem(ctx, wishlistID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockRepository)(nil).DeleteItem), ctx, wishlistID, productID)
}

// GetItems mocks base method.
func (m *MockRepository) GetItems(ctx context.Context, wishlistID uuid.UUID) ([]dbgen.GetWishlistItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, wishlistID)
	ret0, _ := ret[0].([]dbgen.GetWishlistItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockRepositoryMockRecorder) GetItems(ctx, wishlistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockRepository)(nil).GetItems), ctx, wishlistID)
}

// GetOrCreateWishlist mocks base method.
func (m *MockRepository) GetOrCreateWishlist(ctx context.Context, userID uuid.UUID) (dbgen.Wishlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateWishlist", ctx, userID)
	ret0, _ := ret[0].(dbgen.Wishlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateWishlist indicates an expected call of GetOrCreateWishlist.
func (mr *MockRepositoryMockRecorder) GetOrCreateWishlist(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateWishlist", reflect.TypeOf((*MockRepository)(nil).GetOrCreateWishlist), ctx, userID)
}

// GetWishlistByUserID mocks base method.
func (m *MockRepository) GetWishlistByUserID(ctx context.Context, userID uuid.UUID) (dbgen.Wishlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWishlistByUserID", ctx, userID)
	ret0, _ := ret[0].(dbgen.Wishlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWishlistByUserID indicates an expected call of GetWishlistByUserID.
func (mr *MockRepositoryMockRecorder) GetWishlistByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWishlistByUserID", reflect.TypeOf((*MockRepository)(nil).GetWishlistByUserID), ctx, userID)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx dbgen.DBTX) wishlist.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(wishlist.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
