// Code generated by MockGen. DO NOT EDIT.
// Source: midtrans_service.go
//
// Generated by this command:
//
//	mockgen -source=midtrans_service.go -destination=../mock/midtrans/midtrans_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	midtrans "go-gadget-api/internal/midtrans"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateTransactionToken mocks base method.
func (m *MockService) CreateTransactionToken(req *midtrans.CreateTransactionRequest) (*midtrans.CreateTransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionToken", req)
	ret0, _ := ret[0].(*midtrans.CreateTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionToken indicates an expected call of CreateTransactionToken.
func (mr *MockServiceMockRecorder) CreateTransactionToken(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionToken", reflect.TypeOf((*MockService)(nil).CreateTransactionToken), req)
}
