// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard_service.go
//
// Generated by this command:
//
//	mockgen -source=dashboard_service.go -destination=../mock/dashboard/dashboard_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dashboard "go-gadget-api/internal/dashboard"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetDashboardData mocks base method.
func (m *MockService) GetDashboardData(ctx context.Context) (dashboard.DashboardResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardData", ctx)
	ret0, _ := ret[0].(dashboard.DashboardResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardData indicates an expected call of GetDashboardData.
func (mr *MockServiceMockRecorder) GetDashboardData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardData", reflect.TypeOf((*MockService)(nil).GetDashboardData), ctx)
}
