// Code generated by MockGen. DO NOT EDIT.
// Source: dashboard_repo.go
//
// Generated by this command:
//
//	mockgen -source=dashboard_repo.go -destination=../mock/dashboard/dashboard_repo_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dbgen "go-gadget-api/internal/shared/database/dbgen"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetCategoryDistribution mocks base method.
func (m *MockRepository) GetCategoryDistribution(ctx context.Context) ([]dbgen.GetCategoryDistributionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryDistribution", ctx)
	ret0, _ := ret[0].([]dbgen.GetCategoryDistributionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryDistribution indicates an expected call of GetCategoryDistribution.
func (mr *MockRepositoryMockRecorder) GetCategoryDistribution(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryDistribution", reflect.TypeOf((*MockRepository)(nil).GetCategoryDistribution), ctx)
}

// GetStats mocks base method.
func (m *MockRepository) GetStats(ctx context.Context) (dbgen.GetDashboardStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(dbgen.GetDashboardStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRepository)(nil).GetStats), ctx)
}

// ListRecentOrders mocks base method.
func (m *MockRepository) ListRecentOrders(ctx context.Context, limit int32) ([]dbgen.ListRecentOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentOrders", ctx, limit)
	ret0, _ := ret[0].([]dbgen.ListRecentOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentOrders indicates an expected call of ListRecentOrders.
func (mr *MockRepositoryMockRecorder) ListRecentOrders(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentOrders", reflect.TypeOf((*MockRepository)(nil).ListRecentOrders), ctx, limit)
}
