// Code generated by MockGen. DO NOT EDIT.
// Source: cart_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	cart "go-gadget-api/internal/cart"
	dbgen "go-gadget-api/internal/dbgen"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockRepository) AddItem(ctx context.Context, arg dbgen.AddCartItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockRepositoryMockRecorder) AddItem(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockRepository)(nil).AddItem), ctx, arg)
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context, cartID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, cartID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx, cartID)
}

// CreateCart mocks base method.
func (m *MockRepository) CreateCart(ctx context.Context, userID uuid.UUID) (dbgen.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCart", ctx, userID)
	ret0, _ := ret[0].(dbgen.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCart indicates an expected call of CreateCart.
func (mr *MockRepositoryMockRecorder) CreateCart(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCart", reflect.TypeOf((*MockRepository)(nil).CreateCart), ctx, userID)
}

// DecrementQty mocks base method.
func (m *MockRepository) DecrementQty(ctx context.Context, cartID, productID uuid.UUID) (dbgen.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementQty", ctx, cartID, productID)
	ret0, _ := ret[0].(dbgen.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementQty indicates an expected call of DecrementQty.
func (mr *MockRepositoryMockRecorder) DecrementQty(ctx, cartID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementQty", reflect.TypeOf((*MockRepository)(nil).DecrementQty), ctx, cartID, productID)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, cartID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, cartID)
}

// DeleteAllItem mocks base method.
func (m *MockRepository) DeleteAllItem(ctx context.Context, cartID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllItem", ctx, cartID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllItem indicates an expected call of DeleteAllItem.
func (mr *MockRepositoryMockRecorder) DeleteAllItem(ctx, cartID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllItem", reflect.TypeOf((*MockRepository)(nil).DeleteAllItem), ctx, cartID)
}

// DeleteItem mocks base method.
func (m *MockRepository) DeleteItem(ctx context.Context, cartID, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, cartID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockRepositoryMockRecorder) DeleteItem(ctx, cartID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockRepository)(nil).DeleteItem), ctx, cartID, productID)
}

// GetByUserID mocks base method.
func (m *MockRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (dbgen.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(dbgen.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockRepository)(nil).GetByUserID), ctx, userID)
}

// GetDetail mocks base method.
func (m *MockRepository) GetDetail(ctx context.Context, userID uuid.UUID) ([]dbgen.GetCartDetailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, userID)
	ret0, _ := ret[0].([]dbgen.GetCartDetailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockRepositoryMockRecorder) GetDetail(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockRepository)(nil).GetDetail), ctx, userID)
}

// GetItemByCartAndProduct mocks base method.
func (m *MockRepository) GetItemByCartAndProduct(ctx context.Context, cartID, productID uuid.UUID) (dbgen.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByCartAndProduct", ctx, cartID, productID)
	ret0, _ := ret[0].(dbgen.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByCartAndProduct indicates an expected call of GetItemByCartAndProduct.
func (mr *MockRepositoryMockRecorder) GetItemByCartAndProduct(ctx, cartID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByCartAndProduct", reflect.TypeOf((*MockRepository)(nil).GetItemByCartAndProduct), ctx, cartID, productID)
}

// IncrementQty mocks base method.
func (m *MockRepository) IncrementQty(ctx context.Context, cartID, productID uuid.UUID) (dbgen.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementQty", ctx, cartID, productID)
	ret0, _ := ret[0].(dbgen.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementQty indicates an expected call of IncrementQty.
func (mr *MockRepositoryMockRecorder) IncrementQty(ctx, cartID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementQty", reflect.TypeOf((*MockRepository)(nil).IncrementQty), ctx, cartID, productID)
}

// UpdateQty mocks base method.
func (m *MockRepository) UpdateQty(ctx context.Context, arg dbgen.UpdateCartItemQtyParams) (dbgen.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQty", ctx, arg)
	ret0, _ := ret[0].(dbgen.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateQty indicates an expected call of UpdateQty.
func (mr *MockRepositoryMockRecorder) UpdateQty(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQty", reflect.TypeOf((*MockRepository)(nil).UpdateQty), ctx, arg)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(tx dbgen.DBTX) cart.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(cart.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), tx)
}
